function [model, stdevs] = ssm_model_from_samples(samples)

mu_0 = zeros([size(samples(1).model.mu_0) length(samples)]);
Sigma_0 = zeros([size(samples(1).model.Sigma_0) length(samples)]);
Phi = zeros([size(samples(1).model.Phi) length(samples)]);
Upsilon = zeros([size(samples(1).model.Upsilon) length(samples)]);
Bmax = zeros([size(samples(1).model.U.Bmax) length(samples)]);
r_B = zeros([size(samples(1).model.U.r_B) length(samples)]);
Emax = zeros([size(samples(1).model.U.Emax) length(samples)]);
EC50 = zeros([size(samples(1).model.U.EC50) length(samples)]);
Q = zeros([size(samples(1).model.Q) length(samples)]);
A = zeros([size(samples(1).model.A) length(samples)]);
R = zeros([size(samples(1).model.R) length(samples)]);
for i = 1:length(samples)
    mu_0(:,:,i) = samples(i).model.mu_0;
    Sigma_0(:,:,i) = samples(i).model.Sigma_0;
    Phi(:,:,i) = samples(i).model.Phi;
    Upsilon(:,:,i) = samples(i).model.Upsilon;
    Bmax(:,:,i) = samples(i).model.U.Bmax;
    r_B(:,:,i) = samples(i).model.U.r_B;
    Emax(:,:,i) = samples(i).model.U.Emax;
    EC50(:,:,i) = samples(i).model.U.EC50;
    Q(:,:,i) = samples(i).model.Q;
    A(:,:,i) = samples(i).model.A;
    R(:,:,i) = samples(i).model.R;
end

model.mu_0 = mean(mu_0,3);
stdevs.mu_0 = std(mu_0,0,3);
model.Sigma_0 = mean(Sigma_0,3);
stdevs.Sigma_0 = std(Sigma_0,0,3);
model.Phi = mean(Phi,3);
stdevs.Phi = std(Phi,0,3);
model.Upsilon = mean(Upsilon,3);
stdevs.Upsilon = std(Upsilon,0,3);
model.U.Bmax = mean(Bmax,3);
stdevs.U.Bmax = std(Bmax,0,3);
model.U.r_B = mean(r_B,3);
stdevs.U.r_B = std(r_B,0,3);
model.U.Emax = mean(Emax,3);
stdevs.U.Emax = std(Emax,0,3);
model.U.EC50 = mean(EC50,3);
stdevs.U.EC50 = std(EC50,0,3);
model.Q = mean(Q,3);
stdevs.Q = std(Q,0,3);
model.A = mean(A,3);
stdevs.A = std(A,0,3);
model.R = mean(R,3);
stdevs.R = std(R,0,3);